# Nordcast - Ingestion data

In [1]:
import pandas as pd

df2 = pd.read_csv("data/raw/smhi-opendata_19_71380_200603_201602.csv", sep=";", skiprows=11)
df1 = pd.read_csv("data/raw/smhi-opendata_19_71380_201602_202601.csv", sep=";", skiprows=11)

## Control of ingested data

In [2]:
df1.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Lufttemperatur,Kvalitet,Lufttemperatur.1,Kvalitet.1,Unnamed: 7,Tidsutsnitt:
0,2016-02-01 18:00:01,2016-02-02 18:00:00,2016-02-02,4.1,Y,7.3,Y,NaN,NaN
1,2016-02-02 18:00:01,2016-02-03 18:00:00,2016-02-03,2.6,Y,6.0,Y,NaN,NaN
2,2016-02-03 18:00:01,2016-02-04 18:00:00,2016-02-04,2.6,Y,4.2,Y,NaN,NaN
3,2016-02-04 18:00:01,2016-02-05 18:00:00,2016-02-05,2.0,Y,3.5,Y,NaN,NaN
4,2016-02-05 18:00:01,2016-02-06 18:00:00,2016-02-06,2.7,Y,5.0,Y,NaN,NaN

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3652 entries, 0 to 3651
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Från Datum Tid (UTC)  3652 non-null   object
 1   Till Datum Tid (UTC)  3652 non-null   object
 2   Representativt dygn   3652 non-null   object
 3   Lufttemperatur        3652 non-null   float64
 4   Kvalitet              3652 non-null   object
 5   Lufttemperatur.1      3652 non-null   float64
 6   Kvalitet.1            3652 non-null   object
 7   Unnamed: 7            0 non-null      float64
 8   Tidsutsnitt:          0 non-null      float64
dtypes: float64(4), object(5)
memory usage: 256.9+ KB

In [4]:
df2.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Lufttemperatur,Kvalitet,Lufttemperatur.1,Kvalitet.1,Unnamed: 7,Tidsutsnitt:
0,2007-05-31 18:00:01,2007-06-01 18:00:00,2007-06-01,10.3,G,16.9,G,NaN,NaN
1,2007-06-01 18:00:01,2007-06-02 18:00:00,2007-06-02,10.0,G,20.1,G,NaN,NaN
2,2007-06-02 18:00:01,2007-06-03 18:00:00,2007-06-03,10.5,G,19.9,G,NaN,NaN
3,2007-06-03 18:00:01,2007-06-04 18:00:00,2007-06-04,14.0,Y,20.5,Y,NaN,NaN
4,2007-06-04 18:00:01,2007-06-05 18:00:00,2007-06-05,16.1,G,20.3,G,NaN,NaN

In [5]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3197 entries, 0 to 3196
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Från Datum Tid (UTC)  3197 non-null   object
 1   Till Datum Tid (UTC)  3197 non-null   object
 2   Representativt dygn   3197 non-null   object
 3   Lufttemperatur        3197 non-null   float64
 4   Kvalitet              3197 non-null   object
 5   Lufttemperatur.1      3197 non-null   float64
 6   Kvalitet.1            3197 non-null   object
 7   Unnamed: 7            0 non-null      float64
 8   Tidsutsnitt:          0 non-null      float64
dtypes: float64(4), object(5)
memory usage: 224.9+ KB

### Concat all dataframes

In [7]:
all_df = pd.concat([df1, df2], ignore_index=True)

all_df.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Lufttemperatur,Kvalitet,Lufttemperatur.1,Kvalitet.1,Unnamed: 7,Tidsutsnitt:
0,2016-02-01 18:00:01,2016-02-02 18:00:00,2016-02-02,4.1,Y,7.3,Y,NaN,NaN
1,2016-02-02 18:00:01,2016-02-03 18:00:00,2016-02-03,2.6,Y,6.0,Y,NaN,NaN
2,2016-02-03 18:00:01,2016-02-04 18:00:00,2016-02-04,2.6,Y,4.2,Y,NaN,NaN
3,2016-02-04 18:00:01,2016-02-05 18:00:00,2016-02-05,2.0,Y,3.5,Y,NaN,NaN
4,2016-02-05 18:00:01,2016-02-06 18:00:00,2016-02-06,2.7,Y,5.0,Y,NaN,NaN

In [ ]:
all_df.info()

### Change names on columns

In [ ]:
data = { 
    'Representativt dygn': 'date',
    'Lufttemperatur': 'temp_min',
    'Lufttemperatur.1': 'temp_max',
    'Kvalitet': 'quality_min',
    'Kvalitet.1': 'quality_max'
}

all_df = all_df.rename(columns=data)

all_df

###  Take away unnecssary columns

In [ ]:
all_df = all_df.drop(columns=['Unnamed: 7', 'Tidsutsnitt:'])

all_df.head()

### Convert date

In [ ]:
all_df['date'] = pd.to_datetime(all_df['date'])

In [ ]:
all_df.info()

In [ ]:
df = all_df.set_index('date').sort_index()

df.head()

### Deal with qualityflags & make it binary

In [ ]:
all_df['quality_flag'] = (
    (all_df['quality_min'] != 'G') |
    (all_df['quality_max'] != 'G')
).astype(int)

all_df.sample(5)

In [ ]:
duplicates = all_df[all_df.duplicated()]

duplicates

In [ ]:
duplicates = all_df.drop_duplicates()

all_df = duplicates

all_df

In [ ]:
all_df = all_df.drop(columns=["Från Datum Tid (UTC)", "Till Datum Tid (UTC)"])

In [ ]:
all_df

In [ ]:
all_df.to_csv('data/cleaned_smhi_data.csv', index=True)