# Nordcast - Ingestion data

In [ ]:
import pandas as pd

df3 = pd.read_csv("data/smhi-opendata_19_71380_199604_200603.csv", sep=";", skiprows=11)
df2 = pd.read_csv("data/smhi-opendata_19_71380_199604_200603.csv", sep=";", skiprows=11)
df1 = pd.read_csv("data/smhi-opendata_19_71380_201602_202601.csv", sep=";", skiprows=11)

## Control of ingested data

In [5]:
df1.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Lufttemperatur,Kvalitet,Lufttemperatur.1,Kvalitet.1,Unnamed: 7,Tidsutsnitt:
0,2016-02-01 18:00:01,2016-02-02 18:00:00,2016-02-02,4.1,Y,7.3,Y,NaN,NaN
1,2016-02-02 18:00:01,2016-02-03 18:00:00,2016-02-03,2.6,Y,6.0,Y,NaN,NaN
2,2016-02-03 18:00:01,2016-02-04 18:00:00,2016-02-04,2.6,Y,4.2,Y,NaN,NaN
3,2016-02-04 18:00:01,2016-02-05 18:00:00,2016-02-05,2.0,Y,3.5,Y,NaN,NaN
4,2016-02-05 18:00:01,2016-02-06 18:00:00,2016-02-06,2.7,Y,5.0,Y,NaN,NaN

In [13]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3652 entries, 0 to 3651
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Från Datum Tid (UTC)  3652 non-null   object
 1   Till Datum Tid (UTC)  3652 non-null   object
 2   Representativt dygn   3652 non-null   object
 3   Lufttemperatur        3652 non-null   float64
 4   Kvalitet              3652 non-null   object
 5   Lufttemperatur.1      3652 non-null   float64
 6   Kvalitet.1            3652 non-null   object
 7   Unnamed: 7            0 non-null      float64
 8   Tidsutsnitt:          0 non-null      float64
dtypes: float64(4), object(5)
memory usage: 256.9+ KB

In [6]:
df2.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Lufttemperatur,Kvalitet,Lufttemperatur.1,Kvalitet.1,Unnamed: 7,Tidsutsnitt:
0,1996-04-01 18:00:01,1996-04-02 18:00:00,1996-04-02,-4.0,G,2.0,G,NaN,NaN
1,1996-04-02 18:00:01,1996-04-03 18:00:00,1996-04-03,1.0,G,4.4,G,NaN,NaN
2,1996-04-03 18:00:01,1996-04-04 18:00:00,1996-04-04,2.0,G,4.0,G,NaN,NaN
3,1996-04-04 18:00:01,1996-04-05 18:00:00,1996-04-05,0.8,G,3.4,G,NaN,NaN
4,1996-04-05 18:00:01,1996-04-06 18:00:00,1996-04-06,0.2,G,9.1,G,NaN,NaN

In [15]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Från Datum Tid (UTC)  608 non-null    object
 1   Till Datum Tid (UTC)  608 non-null    object
 2   Representativt dygn   608 non-null    object
 3   Lufttemperatur        608 non-null    float64
 4   Kvalitet              608 non-null    object
 5   Lufttemperatur.1      608 non-null    float64
 6   Kvalitet.1            608 non-null    object
 7   Unnamed: 7            0 non-null      float64
 8   Tidsutsnitt:          0 non-null      float64
dtypes: float64(4), object(5)
memory usage: 42.9+ KB

In [12]:
df3.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Lufttemperatur,Kvalitet,Lufttemperatur.1,Kvalitet.1,Unnamed: 7,Tidsutsnitt:
0,1996-04-01 18:00:01,1996-04-02 18:00:00,1996-04-02,-4.0,G,2.0,G,NaN,NaN
1,1996-04-02 18:00:01,1996-04-03 18:00:00,1996-04-03,1.0,G,4.4,G,NaN,NaN
2,1996-04-03 18:00:01,1996-04-04 18:00:00,1996-04-04,2.0,G,4.0,G,NaN,NaN
3,1996-04-04 18:00:01,1996-04-05 18:00:00,1996-04-05,0.8,G,3.4,G,NaN,NaN
4,1996-04-05 18:00:01,1996-04-06 18:00:00,1996-04-06,0.2,G,9.1,G,NaN,NaN

In [16]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 608 entries, 0 to 607
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Från Datum Tid (UTC)  608 non-null    object
 1   Till Datum Tid (UTC)  608 non-null    object
 2   Representativt dygn   608 non-null    object
 3   Lufttemperatur        608 non-null    float64
 4   Kvalitet              608 non-null    object
 5   Lufttemperatur.1      608 non-null    float64
 6   Kvalitet.1            608 non-null    object
 7   Unnamed: 7            0 non-null      float64
 8   Tidsutsnitt:          0 non-null      float64
dtypes: float64(4), object(5)
memory usage: 42.9+ KB

### Concat all dataframes

In [8]:
all_df = pd.concat([df1, df2, df3], ignore_index=True)

all_df.head()

,Från Datum Tid (UTC),Till Datum Tid (UTC),Representativt dygn,Lufttemperatur,Kvalitet,Lufttemperatur.1,Kvalitet.1,Unnamed: 7,Tidsutsnitt:
0,2016-02-01 18:00:01,2016-02-02 18:00:00,2016-02-02,4.1,Y,7.3,Y,NaN,NaN
1,2016-02-02 18:00:01,2016-02-03 18:00:00,2016-02-03,2.6,Y,6.0,Y,NaN,NaN
2,2016-02-03 18:00:01,2016-02-04 18:00:00,2016-02-04,2.6,Y,4.2,Y,NaN,NaN
3,2016-02-04 18:00:01,2016-02-05 18:00:00,2016-02-05,2.0,Y,3.5,Y,NaN,NaN
4,2016-02-05 18:00:01,2016-02-06 18:00:00,2016-02-06,2.7,Y,5.0,Y,NaN,NaN

In [10]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4868 entries, 0 to 4867
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Från Datum Tid (UTC)  4868 non-null   object
 1   Till Datum Tid (UTC)  4868 non-null   object
 2   Representativt dygn   4868 non-null   object
 3   Lufttemperatur        4868 non-null   float64
 4   Kvalitet              4868 non-null   object
 5   Lufttemperatur.1      4868 non-null   float64
 6   Kvalitet.1            4868 non-null   object
 7   Unnamed: 7            0 non-null      float64
 8   Tidsutsnitt:          0 non-null      float64
dtypes: float64(4), object(5)
memory usage: 342.4+ KB

## Exploring columns

In [22]:
all_df["Unnamed: 7"].value_counts()

Series([], Name: count, dtype: int64)

In [23]:
all_df["Tidsutsnitt:"].value_counts()

Series([], Name: count, dtype: int64)

## Dropping empty columns

In [25]:
all_df = all_df.dropna(axis=1, how="all")

all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4868 entries, 0 to 4867
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Från Datum Tid (UTC)  4868 non-null   object
 1   Till Datum Tid (UTC)  4868 non-null   object
 2   Representativt dygn   4868 non-null   object
 3   Lufttemperatur        4868 non-null   float64
 4   Kvalitet              4868 non-null   object
 5   Lufttemperatur.1      4868 non-null   float64
 6   Kvalitet.1            4868 non-null   object
dtypes: float64(2), object(5)
memory usage: 266.3+ KB